name: samprod
channels:
  - defaults
dependencies:
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pip
  - pandas
  - python=3.10
  - scikit-learn
  - pip:
    - pylatex
    - shap
    - stroke-outcome
    - xgboost
